name: Publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Run Tests
        run: deno test test.ts

      - name: Publish package
        run: npx jsr publish
